# Generated by Django 5.1.1 on 2024-12-28 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedagogicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(choices=[('الأولى', 'الأولى'), ('الثانية', 'الثانية')], max_length=20)),
                ('contrat', models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني'), ('الثالث', 'الثالث'), ('الرابع', 'الرابع')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('coeficient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='student_master.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='student_master.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birth_day', models.DateField(default=django.utils.timezone.now)),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_place_en', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_wilaya', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('pedagogic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_master.pedagogicyear')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_master.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default='111', max_length=50, unique=True)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('academic_year', models.CharField(default='2025/2024', max_length=11)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('pedagogic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_master.pedagogicyear')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_master.speciality')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_master.student')),
            ],
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0)),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_status', models.CharField(choices=[('ناجح', 'ناجح'), ('معيد', 'معيد'), ('مفصول', 'مفصول')], default='ناجح', max_length=20)),
                ('decision_date', models.DateField(default=django.utils.timezone.now)),
                ('diploma_issued', models.BooleanField(default=False)),
                ('transcript_issued', models.BooleanField(default=False)),
                ('pedagogic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='student_master.pedagogicyear')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='student_master.speciality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='student_master.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session', models.CharField(choices=[('العادية', 'العادية'), ('تعويضية', 'تعويضية')], default='العادية', max_length=20)),
                ('pedagogic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_master.pedagogicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_master.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_master.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unities', to='student_master.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student_master.unity'),
        ),
    ]
