# Generated by Django 5.1.1 on 2024-12-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pedagogic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='speciality',
        ),
    ]
