# Generated by Django 5.1.1 on 2024-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0002_remove_student_pedagogic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='academic_year',
            field=models.CharField(default='2025/2024', max_length=11),
        ),
    ]
