# Generated by Django 5.1.1 on 2024-12-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0003_deliberation_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation',
            name='academic_year',
            field=models.CharField(choices=[('2025/2024', '2025/2024'), ('2024/2023', '2024/2023'), ('2023/2022', '2023/2022'), ('2022/2021', '2022/2021'), ('2021/2020', '2021/2020'), ('2020/2019', '2020/2019'), ('2019/2018', '2019/2018'), ('2018/2017', '2018/2017'), ('2017/2016', '2017/2016'), ('2016/2015', '2016/2015'), ('2015/2014', '2015/2014'), ('2014/2013', '2014/2013'), ('2013/2012', '2013/2012'), ('2012/2011', '2012/2011'), ('2011/2010', '2011/2010'), ('2010/2009', '2010/2009'), ('2009/2008', '2009/2008'), ('2008/2007', '2008/2007'), ('2007/2006', '2007/2006'), ('2006/2005', '2006/2005'), ('2005/2004', '2005/2004'), ('2004/2003', '2004/2003'), ('2003/2002', '2003/2002'), ('2002/2001', '2002/2001'), ('2001/2000', '2001/2000')], default='2024/2023', max_length=9),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='result_status',
            field=models.CharField(choices=[('ناجح', 'ناجح'), ('معيد', 'معيد'), ('منقطع', 'منقطع')], default='ناجح', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_specialities', to='student_master.speciality'),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_students', to='student_master.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(choices=[('2025/2024', '2025/2024'), ('2024/2023', '2024/2023'), ('2023/2022', '2023/2022'), ('2022/2021', '2022/2021'), ('2021/2020', '2021/2020'), ('2020/2019', '2020/2019'), ('2019/2018', '2019/2018'), ('2018/2017', '2018/2017'), ('2017/2016', '2017/2016'), ('2016/2015', '2016/2015'), ('2015/2014', '2015/2014'), ('2014/2013', '2014/2013'), ('2013/2012', '2013/2012'), ('2012/2011', '2012/2011'), ('2011/2010', '2011/2010'), ('2010/2009', '2010/2009'), ('2009/2008', '2009/2008'), ('2008/2007', '2008/2007'), ('2007/2006', '2007/2006'), ('2006/2005', '2006/2005'), ('2005/2004', '2005/2004'), ('2004/2003', '2004/2003'), ('2003/2002', '2003/2002'), ('2002/2001', '2002/2001'), ('2001/2000', '2001/2000')], default='2024/2023', max_length=9),
        ),
        migrations.AlterField(
            model_name='subject',
            name='coeficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficient', models.IntegerField(default=1)),
                ('credit', models.IntegerField(default=0)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoire_specialities', to='student_master.speciality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoire_students', to='student_master.student')),
            ],
        ),
    ]
