# Generated by Django 5.1.1 on 2024-12-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0006_unity_pedagogic_year_alter_enrollment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='session',
            field=models.CharField(choices=[('العادية', 'العادية'), ('تعويضية', 'تعويضية')], default='العادية', max_length=20),
        ),
    ]
