# Generated by Django 5.1.1 on 2024-12-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0007_memoire_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='mention',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('قريب من الجيد', 'قريب من الجيد'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز')], default='', max_length=20),
        ),
    ]
