# Generated by Django 5.1.1 on 2025-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0009_alter_deliberation_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation',
            name='mention',
            field=models.CharField(choices=[('/', '/'), ('مقبول', 'مقبول'), ('قريب من الجيد', 'قريب من الجيد'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز')], default='/', max_length=20),
        ),
    ]
