# Generated by Django 5.1.1 on 2025-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0010_alter_deliberation_mention'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliberation',
            name='unique_student_deliberation',
        ),
        migrations.AddConstraint(
            model_name='deliberation',
            constraint=models.UniqueConstraint(fields=('student', 'pedagogic_year'), name='unique_student_pedagogic_year_deliberation'),
        ),
    ]
