# Generated by Django 5.1.1 on 2025-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0011_remove_deliberation_unique_student_deliberation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='matricule',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
