# Generated by Django 5.1.1 on 2025-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0013_grade_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
