# Generated by Django 5.1.1 on 2025-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0014_alter_unity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='diploma_number',
            field=models.IntegerField(default=0),
        ),
    ]
