# Generated by Django 5.1.1 on 2025-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0017_alter_student_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_wilaya_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
