# Generated by Django 5.1.1 on 2025-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0018_student_birth_wilaya_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='ex_entreprise',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
