# Generated by Django 5.1.1 on 2025-01-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0021_memoire_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='pedagogic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_master.pedagogicyear'),
        ),
    ]
