# Generated by Django 5.1.1 on 2025-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0022_alter_enrollment_pedagogic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_en', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_wilaya_en', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('live_wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='session',
            field=models.CharField(choices=[('العادية', 'العادية'), ('الثانية', 'الثانية')], default='العادية', max_length=20),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='session',
            field=models.CharField(choices=[('العادية', 'العادية'), ('الثانية', 'الثانية')], default='العادية', max_length=20),
        ),
    ]
