# Generated by Django 5.1.1 on 2025-02-06 22:30

import student_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0025_memoire_memoire_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='memoire_file',
            field=models.FileField(blank=True, null=True, upload_to=student_master.models.memoire_file_upload_path),
        ),
    ]
