# Generated by Django 5.1.1 on 2025-02-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0026_alter_memoire_memoire_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
