# Generated by Django 5.1.1 on 2025-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0028_enrollment_issued_badge_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='transcript_issued',
            new_name='badge_issued',
        ),
    ]
