# Generated by Django 5.1.1 on 2025-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0029_rename_transcript_issued_enrollment_badge_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='matricule',
            field=models.CharField(default='', max_length=50),
        ),
    ]
