# Generated by Django 5.1.1 on 2025-02-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0031_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_contrat',
            new_name='StudentContrat',
        ),
    ]
