# Generated by Django 5.1.1 on 2025-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0032_rename_student_contrat_studentcontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontrat',
            name='branch',
            field=models.CharField(choices=[('رياضيات', 'رياضيات'), ('فيزياء', 'فيزياء'), ('إعلام ألي', 'إعلام ألي'), ('علوم طبيعية', 'علوم طبيعية'), ('موسيقى', 'موسيقى')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentcontrat',
            name='category',
            field=models.CharField(choices=[('أستاذ التعليم المتوسط', 'أستاذ التعليم المتوسط'), ('أستاذ التعليم الثانوي', 'أستاذ التعليم الثانوي')], default='', max_length=50),
        ),
    ]
