# Generated by Django 5.1.1 on 2025-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_master', '0033_studentcontrat_branch_studentcontrat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontrat',
            name='sexe',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='', max_length=50),
        ),
    ]
